version: '3.8'

services:
  db:
    image: postgres:15
    container_name: notification_service_db
    environment:
      POSTGRES_USER: modak
      POSTGRES_PASSWORD: modak
      POSTGRES_DB: notification_db
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: notification_redis
    ports:
      - "6379:6379"
    restart: unless-stopped